apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
spec:
  project: default
  source:
    repoURL: https://github.com/yongshing32/techtrends-ys.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
